[book]
authors = ["subfish-zhou"]
language = "zh"
multilingual = false
src = "src"
title = "Lean中文教程"

[output.html]
git-repository-url = "https://github.com/subfish-zhou/theorem_proving_in_lean4_zh_CN"

[output.html.playground.boring-prefixes]
lean = "# "